name: rlkit
channels:
  - pytorch
  - kne
  - menpo
  - asmeurer
  - anaconda
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2021.1.19
  - cairo=1.14.8
  - certifi=2020.6.20
  - cffi=1.11.5
  - cycler=0.10.0
  - cython=0.28.5
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - fontconfig=2.12.1
  - freetype=2.5.5
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=0.9.35
  - hdf5=1.10.2
  - icu=54.1
  - intel-openmp=2020.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - joblib=0.9.4
  - jpeg=9b
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.14
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libxcb=1.14
  - libxml2=2.9.9
  - llvmlite=0.20.0
  - lockfile=0.12.2
  - mako=1.0.6
  - markupsafe=1.0
  - matplotlib=2.0.2
  - mkl=2018.0.2
  - ninja=1.8.2
  - numba=0.35.0
  - numpy=1.11.3
  - opencv=3.4.1
  - opencv3=3.1.0
  - openssl=1.0.2u
  - pango=1.36.8
  - patchelf=0.12
  - path.py=10.3.1
  - pcre=8.44
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pixman=0.34.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pybox2d=2.3.1post2
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.6.0
  - python=3.5.2
  - python-dateutil=2.6.1
  - pytorch-cpu=0.4.1
  - pytz=2020.1
  - qt=5.6.2
  - readline=6.2
  - scipy=1.0.1
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.15.0
  - sqlite=3.13.0
  - tk=8.5.18
  - traitlets=4.3.2
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - atari-py==0.2.6
    - box2d-kengz==2.3.3
    - chardet==4.0.0
    - cloudpickle==0.5.2
    - future==0.18.2
    - gitdb==4.0.5
    - gitdb2==4.0.2
    - gitpython==2.1.7
    - glfw==2.0.0
    - gtimer==1.0.0b5
    - gym==0.10.5
    - idna==2.10
    - imageio==2.9.0
    - ipdb==0.13.4
    - mujoco-py==2.0.2.5
    - parso==0.7.1
    - pillow==7.2.0
    - pip==10.0.0
    - pygame==1.9.2
    - pyglet==1.3.2
    - pyopengl==3.1.5
    - requests==2.25.1
    - smmap==3.0.5
    - urllib3==1.26.2
